name: Deploy Backend to ECS

on:
  push:
    branches:
      - main  # only deploy when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::132418765186:role/GithubActionsDeploy-Backend
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          IMAGE_TAG=latest
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_REPO=nicsan-crm-api
          docker build -t $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG ./nicsan-crm-backend
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

      - name: Render Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./nicsan-crm-backend/ecs-taskdef.json
          container-name: nicsan-crm-api
          image: ${{ steps.login-ecr.outputs.registry }}/nicsan-crm-api:latest

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: nicsan-crm-api-svc
          cluster: nicsan-crm-prod
          wait-for-service-stability: true
